
import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
  he: {
    // Navigation and common
    home: 'בית',
    myTrips: 'הטיולים שלי',
    travelBloggers: 'בלוגרי טיולים',
    systemSettings: 'הגדרות מערכת',
    bloggerManagement: 'ניהול בלוגרים',
    profile: 'פרופיל',
    bloggerArea: 'אזור בלוגרים',
    settings: 'הגדרות',
    logout: 'התנתק',
    login: 'התחבר',
    language: 'שפה',
    about: 'אודות',
    aboutUs: 'אודותינו',
    ourTeam: 'הצוות שלנו',
    careers: 'קריירה',
    blog: 'בלוג',
    support: 'תמיכה',
    contactUs: 'צור קשר',
    faq: 'שאלות נפוצות',
    helpCenter: 'מרכז עזרה',
    legal: 'משפטי',
    terms: 'תנאי שימוש',
    privacy: 'פרטיות',
    refunds: 'החזרים',
    bloggers: 'בלוגרים',
    applyToBeBlogger: 'הגש מועמדות לבלוגר',
    
    // Trip related
    planNewTrip: 'תכנן טיול חדש',
    tripItinerary: 'מסלול הטיול',
    day: 'יום',
    nextDay: 'היום הבא',
    previousDay: 'היום הקודם',
    travelChatTitle: 'צ\'אט טיול',
    travelChatPrompt: 'איך אוכל לעזור לך עם הטיול?',
    travelChatExample: 'לדוגמה: "הוסף יום נוסף" או "שנה את היום השלישי"',
    whatToChange: 'מה תרצה לשנות?',
    
    // Status
    draft: 'טיוטה',
    planning: 'בתכנון',
    booked: 'הוזמן',
    completed: 'הושלם',
    cancelled: 'בוטל',
    
    // General
    error: 'שגיאה',
    loading: 'טוען...',
    loadingItinerary: 'טוען מסלול...',
    noTripsYet: 'אין לך טיולים עדיין',
    noTripsFound: 'עדיין לא תכננת טיולים. בוא נתחיל!',
    adults: 'מבוגרים',
    children: 'ילדים',
    days: 'ימים',
    
    // Home Page Additions
    perfectTripWaiting: "הטיול המושלם שלך מחכה",
    smartPlatformDescription: "הפלטפורמה החכמה שלנו לתכנון טיולים תעזור לך ליצור חופשה בלתי נשכחת, מותאמת אישית עבורך",
    startPlanningTrip: "התחל לתכנן טיול",
    enjoyDesertSafari: "תהנה מספארי במדבר",
    enjoySeaBeauty: "תהנה מיופיו של הים",
    enjoyParisTower: "תהנה ממגדל אייפל",
    testimonialsTitle: "מה הלקוחות שלנו אומרים",
    prepareToExplore: "התכונן לחקור את העולם",
    manyOffersWaiting: "יש לנו הרבה הצעות נהדרות בשבילך",
    getStarted: "בוא נתחיל",
    howPlanGoWorks: "איך Plan&Go עובד",
    chooseDates: "בחר תאריכים",
    chooseDatesDesc: "בחר את תאריכי ההתחלה והסיום של הטיול שלך",
    chooseDestination: "בחר יעד",
    chooseDestinationDesc: "בחר לאן תרצה לטייל",
    chooseComponents: "בחר רכיבים",
    chooseComponentsDesc: "בחר טיסות, מלונות ופעילויות",
    bookAndEnjoy: "הזמן ותהנה",
    bookAndEnjoyDesc: "הזמן את הטיול שלך ותהנה מחופשה נהדרת",

    // Plan Trip Page Additions
    planNewVacation: "תכנן את החופשה החדשה שלך",
    tellUsAboutVacation: "ספר לנו על חופשת החלומות שלך ואנו ניצור עבורך מסלול מותאם אישית",
    tripDestination: "יעד הטיול",
    whereToTravel: "לאן תרצו לטייל?",
    tripDates: "תאריכי הטיול",
    departureDate: "תאריך יציאה",
    chooseDepartureDate: "בחר תאריך יציאה",
    returnDate: "תאריך חזרה",
    chooseReturnDate: "בחר תאריך חזרה",
    numberOfTravelers: "מספר נוסעים",
    numAdults: "מספר מבוגרים",
    numChildren: "מספר ילדים",
    childrenAges: "גילאי הילדים",
    child: "ילד",
    budget: "תקציב",
    budgetRange: "טווח תקציב",
    minimum: "מינימום",
    maximum: "מקסימום",
    tripType: "אופי הטיול",
    describeTripType: "תאר את סוג הטיול שתרצה",
    notesDescription: "הערות אלו יעזרו ל-AI לתכנן טיול טוב יותר עבורך.",
    summary: "סיכום",
    tripDetails: "פרטי הטיול",
    destination: "יעד",
    dates: "תאריכים",
    travelers: "נוסעים",
    preferences: "העדפות",
    flights: "טיסות",
    hotels: "מלונות",
    carRental: "השכרת רכב",
    attractions: "אטרקציות",
    restaurants: "מסעדות",
    allReady: "הכל מוכן! בואו ניצור את הטיול שלכם.",
    back: "חזור",
    continue: "המשך",
    clarifyTripDetails: "דיוק פרטי הטיול",
    writeYourAnswer: "כתוב את תשובתך כאן...",
    backToQuestionnaire: "חזרה לשאלון",
    
    // Adaptation page
    whatIsWrongWithActivity: "מה לא מתאים לך בפעילות '{activityTitle}'?",
    oopsCouldNotFindAlternatives: "אופס, לא הצלחתי למצוא חלופות. נסה לנסח אחרת.",
    foundAlternatives: "מצאתי כמה חלופות. בחר את המתאימה לך ביותר:",
    requestAnotherActivity: "בקש פעילות אחרת",
    forExampleMoreRelaxing: "לדוגמה: 'משהו יותר רגוע', 'פחות יקר'",
    select: "בחר",
    adaptTripForMe: 'התאם את הטיול עבורי',
    loadingTripDataOrNotFound: "טוען נתוני טיול או שהטיול לא נמצא",
    missingTripId: "מזהה הטיול חסר",
    originalTripNotFound: "הטיול המקורי לא נמצא",
    errorLoadingOriginalTrip: "שגיאה בטעינת הטיול המקורי: ",
    fillAllRequiredFields: "אנא מלא את כל השדות הנדרשים",
    invalidDateRange: "טווח תאריכים לא תקין",
    preparingTrip: "מכין את הטיול שלך",
    findingSuitableFlight: "מחפש טיסה מתאימה",
    adaptingItineraryToFlightTimes: "מתאים את המסלול לזמני הטיסה",
    savingYourAdaptedTrip: "שומר את הטיול המותאם שלך",
    userNotLoggedIn: "המשתמש לא מחובר",
    flightInfoMissing: "מידע הטיסה חסר",
    emptyItinerary: "מסלול ריק",
    unknownLocation: "מיקום לא ידוע",
    errorSavingTrip: "שגיאה בשמירת הטיול: ",
    reviewChanges: "סקירת השינויים",
    itineraryAdaptedToFlights: "המסלול הותאם לזמני הטיסות",
    outboundFlight: "טיסת יציאה",
    returnFlight: "טיסת חזרה",
    flight: "טיסה",
    backToPreviousStep: "חזרה לשלב הקודם",
    confirmAndSaveTrip: "אשר ושמור טיול",
    thisMayTakeAFewMoments: "זה יכול לקחת כמה רגעים",
    recommendedFlight: "טיסה מומלצת",
    aiWillFindBestFlight: "הבינה המלאכותית תמצא עבורכם את הטיסה הטובה ביותר",
    flightChosenByAI: "טיסה שנבחרה על ידי הבינה המלאכותית",
    adaptTripTitle: "התאמת הטיול '{tripTitle}'",
    makeThisTripPerfect: "בואו נהפוך את הטיול הזה למושלם עבורכם",
    flightWithAirline: "טיסה עם {airline}",
    roundTripFlightWithAirline: "טיסה הלוך-חזור עם {airline}",
    adaptationFailed: "ההתאמה נכשלה",
    tripPreferences: "העדפות הטיול",
    fillDetailsToAdapt: "מלא את הפרטים כדי להתאים את הטיול",
    startDate: "תאריך התחלה",
    selectDate: "בחר תאריך",
    tripWillEndOn: "הטיול יסתיים ב",
    numberOfAdults: "מספר מבוגרים",
    numberOfChildren: "מספר ילדים",
    childrenAges: "גילאי הילדים",
    child: "ילד",
    specialRequests: "בקשות מיוחדות",
    specialRequestsPlaceholder: "יש לך בקשות מיוחדות? ציין כאן...",
    backToForm: "חזרה לטופס"
  },
  en: {
    // Navigation and common
    home: 'Home',
    myTrips: 'My Trips',
    travelBloggers: 'Travel Bloggers',
    systemSettings: 'System Settings',
    bloggerManagement: 'Blogger Management',
    profile: 'Profile',
    bloggerArea: 'Blogger Area',
    settings: 'Settings',
    logout: 'Logout',
    login: 'Login',
    language: 'Language',
    about: 'About',
    aboutUs: 'About Us',
    ourTeam: 'Our Team',
    careers: 'Careers',
    blog: 'Blog',
    support: 'Support',
    contactUs: 'Contact Us',
    faq: 'FAQ',
    helpCenter: 'Help Center',
    legal: 'Legal',
    terms: 'Terms of Service',
    privacy: 'Privacy Policy',
    refunds: 'Refunds',
    bloggers: 'Bloggers',
    applyToBeBlogger: 'Apply to be a Blogger',
    
    // Trip related
    planNewTrip: 'Plan New Trip',
    tripItinerary: 'Trip Itinerary',
    day: 'Day',
    nextDay: 'Next Day',
    previousDay: 'Previous Day',
    travelChatTitle: 'Travel Chat',
    travelChatPrompt: 'How can I help you with your trip?',
    travelChatExample: 'For example: "Add another day" or "Change day three"',
    whatToChange: 'What would you like to change?',
    
    // Status
    draft: 'Draft',
    planning: 'Planning',
    booked: 'Booked',
    completed: 'Completed',
    cancelled: 'Cancelled',
    
    // General
    error: 'Error',
    loading: 'Loading...',
    loadingItinerary: 'Loading itinerary...',
    noTripsYet: 'No trips yet',
    noTripsFound: 'You haven\'t planned any trips yet. Let\'s get started!',
    adults: 'Adults',
    children: 'Children',
    days: 'Days',

    // Home Page Additions
    perfectTripWaiting: "Your perfect trip is waiting",
    smartPlatformDescription: "Our smart trip planning platform will help you create an unforgettable, personalized vacation",
    startPlanningTrip: "Start Planning a Trip",
    enjoyDesertSafari: "Enjoy a Desert Safari",
    enjoySeaBeauty: "Enjoy the Beauty of the Sea",
    enjoyParisTower: "Enjoy the Eiffel Tower",
    testimonialsTitle: "What Our Customers Say",
    prepareToExplore: "Prepare to Explore the World",
    manyOffersWaiting: "We have many great offers waiting for you",
    getStarted: "Get Started",
    howPlanGoWorks: "How Plan&Go Works",
    chooseDates: "Choose Dates",
    chooseDatesDesc: "Select your trip's start and end dates",
    chooseDestination: "Choose Destination",
    chooseDestinationDesc: "Choose where you'd like to travel",
    chooseComponents: "Choose Components",
    chooseComponentsDesc: "Select flights, hotels, and activities",
    bookAndEnjoy: "Book and Enjoy",
    bookAndEnjoyDesc: "Book your trip and enjoy a wonderful vacation",

    // Plan Trip Page Additions
    planNewVacation: "Plan Your New Vacation",
    tellUsAboutVacation: "Tell us about your dream vacation and we will create a personalized itinerary for you",
    tripDestination: "Trip Destination",
    whereToTravel: "Where would you like to travel?",
    tripDates: "Trip Dates",
    departureDate: "Departure Date",
    chooseDepartureDate: "Choose Departure Date",
    returnDate: "Return Date",
    chooseReturnDate: "Choose Return Date",
    numberOfTravelers: "Number of Travelers",
    numAdults: "Number of Adults",
    numChildren: "Number of Children",
    childrenAges: "Children's Ages",
    child: "Child",
    budget: "Budget",
    budgetRange: "Budget Range",
    minimum: "Minimum",
    maximum: "Maximum",
    tripType: "Trip Type",
    describeTripType: "Describe the type of trip you'd like",
    notesDescription: "These notes will help the AI plan a better trip for you.",
    summary: "Summary",
    tripDetails: "Trip Details",
    destination: "Destination",
    dates: "Dates",
    travelers: "Travelers",
    preferences: "Preferences",
    flights: "Flights",
    hotels: "Hotels",
    carRental: "Car Rental",
    attractions: "Attractions",
    restaurants: "Restaurants",
    allReady: "All ready! Let's create your trip.",
    back: "Back",
    continue: "Continue",
    clarifyTripDetails: "Clarify Trip Details",
    writeYourAnswer: "Write your answer here...",
    backToQuestionnaire: "Back to Questionnaire",
    
    // Adaptation page
    whatIsWrongWithActivity: "What's not right for you about the activity '{activityTitle}'?",
    oopsCouldNotFindAlternatives: "Oops, I couldn't find alternatives. Try phrasing it differently.",
    foundAlternatives: "I found some alternatives. Choose the one that suits you best:",
    requestAnotherActivity: "Request Another Activity",
    forExampleMoreRelaxing: "For example: 'something more relaxing', 'less expensive'",
    select: "Select",
    adaptTripForMe: 'Adapt This Trip For Me',
    loadingTripDataOrNotFound: "Loading trip data or trip not found",
    missingTripId: "Trip ID is missing",
    originalTripNotFound: "Original trip not found",
    errorLoadingOriginalTrip: "Error loading original trip: ",
    fillAllRequiredFields: "Please fill all required fields",
    invalidDateRange: "Invalid date range",
    preparingTrip: "Preparing your trip",
    findingSuitableFlight: "Finding suitable flight",
    adaptingItineraryToFlightTimes: "Adapting itinerary to flight times",
    savingYourAdaptedTrip: "Saving your adapted trip",
    userNotLoggedIn: "User not logged in",
    flightInfoMissing: "Flight information missing",
    emptyItinerary: "Empty itinerary",
    unknownLocation: "Unknown location",
    errorSavingTrip: "Error saving trip: ",
    reviewChanges: "Review Changes",
    itineraryAdaptedToFlights: "Itinerary adapted to flight times",
    outboundFlight: "Outbound Flight",
    returnFlight: "Return Flight",
    flight: "Flight",
    backToPreviousStep: "Back to Previous Step",
    confirmAndSaveTrip: "Confirm and Save Trip",
    thisMayTakeAFewMoments: "This may take a few moments",
    recommendedFlight: "Recommended Flight",
    aiWillFindBestFlight: "AI will find the best flight for you",
    flightChosenByAI: "Flight chosen by AI",
    adaptTripTitle: "Adapting Trip '{tripTitle}'",
    makeThisTripPerfect: "Let's make this trip perfect for you",
    flightWithAirline: "Flight with {airline}",
    roundTripFlightWithAirline: "Round trip flight with {airline}",
    adaptationFailed: "Adaptation failed",
    tripPreferences: "Trip Preferences",
    fillDetailsToAdapt: "Fill the details to adapt the trip",
    startDate: "Start Date",
    selectDate: "Select Date",
    tripWillEndOn: "Trip will end on",
    numberOfAdults: "Number of Adults",
    numberOfChildren: "Number of Children",
    childrenAges: "Children Ages",
    child: "Child",
    specialRequests: "Special Requests",
    specialRequestsPlaceholder: "Any special requests? Note them here...",
    backToForm: "Back to Form"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('he');

  const switchLanguage = (newLanguage) => {
    setLanguage(newLanguage);
  };

  const direction = language === 'he' ? 'rtl' : 'ltr';

  const t = (key, params = {}) => {
    let translation = translations[language][key] || key;
    Object.keys(params).forEach(param => {
      translation = translation.replace(`{${param}}`, params[param]);
    });
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, switchLanguage, direction, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
